name: AdvancedEnchantmentsExtras
main: me.egg82.aee.BukkitBootstrap
version: 4.12.15
author: egg82
api-version: 1.13
description: Better Enchantments & Curses
depend: [AdvancedEnchantments]
softdepend: [Plan, ProtocolLib]
loadbefore: [Boss, Confiscate, CoreArena, ChatControl, AutoPlay, Winter, Puncher] # This is absolutely insane, but this somehow solves a random bug. Somehow.