name: AdvancedEnchantments
main: me.egg82.ae.BukkitBootstrap
version: 4.12.16
author: egg82
api-version: 1.13
description: Better Enchantments & Curses
softdepend: [Plan, ProtocolLib]
loadbefore: [Boss, Confiscate, CoreArena, ChatControl, AutoPlay, Winter, Puncher] # This is absolutely insane, but this somehow solves a random bug. Somehow.