# Value between 0 and 1, representing the percentage chance that a custom enchantment will be added to an item while using an enchanting table
# 0 = no chance (off), 1 = 100% chance (all custom enchants, no vanilla)
# If > 0, will add all registered custom enchants to the vanilla enchanting system
# Registered enchants are enchantments that extend AdvancedEnchantment
# For the layman: this will mean most, if not all, custom enchantments
enchant-chance: 0.0

# When enabled, enchants that do extra durability damage bypass unbreaking
# The default is true, which balances the power of the enchants as compared to vanilla
bypass-unbreaking: true

# Whether or not to enable particle effects
particles: true

# Defines chances that enchants/curses appear in loot tables
# 0 = no chance (off), 1 = 100% chance (all items enchanted)
# NOTE: This requires Paper (or a fork of Paper) that has the loot table API
loot-chance:
  # Chance that new enchants appear
  enchant: 0.00045
  # Chance that curses appear
  curse: 0.00126

# When true, logs some extra output to the console so you can see if/why things might be failing
debug: false
# Default language (affects console output)
lang: 'en'

stats:
  # Whether or not to send anonymous usage statistics to bStats
  # True: Send anonymous stats; let the author know how well the plugin is doing and how it's used!
  # False: Do not send stats and make the author sad :(
  usage: true
  # Whether or not to send anonymous errors to the author
  # True: Send errors anonymously to GameAnalytics so the author can fix them!
  # False: Do not send errors and wonder why any bugs you encounter haven't been fixed
  errors: true

update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the ae.admin permission node
  notify: true

# Config version, no touchy plz
version: 1.2